// Generated by gencpp from file offboard_py/position3D.msg
// DO NOT EDIT!


#ifndef OFFBOARD_PY_MESSAGE_POSITION3D_H
#define OFFBOARD_PY_MESSAGE_POSITION3D_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace offboard_py
{
template <class ContainerAllocator>
struct position3D_
{
  typedef position3D_<ContainerAllocator> Type;

  position3D_()
    : x()
    , y()
    , z()  {
    }
  position3D_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , z(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _x_type;
  _x_type x;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _y_type;
  _y_type y;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _z_type;
  _z_type z;





  typedef boost::shared_ptr< ::offboard_py::position3D_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::offboard_py::position3D_<ContainerAllocator> const> ConstPtr;

}; // struct position3D_

typedef ::offboard_py::position3D_<std::allocator<void> > position3D;

typedef boost::shared_ptr< ::offboard_py::position3D > position3DPtr;
typedef boost::shared_ptr< ::offboard_py::position3D const> position3DConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::offboard_py::position3D_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::offboard_py::position3D_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::offboard_py::position3D_<ContainerAllocator1> & lhs, const ::offboard_py::position3D_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.z == rhs.z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::offboard_py::position3D_<ContainerAllocator1> & lhs, const ::offboard_py::position3D_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace offboard_py

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::offboard_py::position3D_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::offboard_py::position3D_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_py::position3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::offboard_py::position3D_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_py::position3D_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::offboard_py::position3D_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::offboard_py::position3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "615bdf149c8f78fd88df8f8f89a7e200";
  }

  static const char* value(const ::offboard_py::position3D_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x615bdf149c8f78fdULL;
  static const uint64_t static_value2 = 0x88df8f8f89a7e200ULL;
};

template<class ContainerAllocator>
struct DataType< ::offboard_py::position3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "offboard_py/position3D";
  }

  static const char* value(const ::offboard_py::position3D_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::offboard_py::position3D_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] x\n"
"float64[] y\n"
"float64[] z\n"
;
  }

  static const char* value(const ::offboard_py::position3D_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::offboard_py::position3D_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position3D_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::offboard_py::position3D_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::offboard_py::position3D_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "z[]" << std::endl;
    for (size_t i = 0; i < v.z.size(); ++i)
    {
      s << indent << "  z[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.z[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // OFFBOARD_PY_MESSAGE_POSITION3D_H
